/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2;

public class Lab2 {

    public static void main(String[] args) {
        Location locA=new Location();
        locA.setName("Iasi");
        System.out.println(locA.getName());
        locA.hasSameName("Iasi");
        locA.toString();
        
        Road roadB=new Road();
        roadB.setType("national");
        roadB.toString();
    }
}
